# Application display name
spring.application.name=SpringDataJpaDemo

# PostgreSQL connection
spring.datasource.url=jdbc:postgresql://localhost:5432/testdb
spring.datasource.username=postgres
spring.datasource.password=pass

# Hibernate: update schema to match entities (does not drop data)
spring.jpa.hibernate.ddl-auto=update
#spring.jpa.hibernate.ddl-auto=create-drop
#spring.jpa.hibernate.ddl-auto=update
#spring.jpa.hibernate.ddl-auto=validate
#spring.jpa.hibernate.ddl-auto=none

# Run data.sql AFTER Hibernate creates/updates tables
spring.jpa.defer-datasource-initialization=true
spring.sql.init.mode=always

# Log SQL for learning/debugging
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

# Secret used by JwtService to sign/verify tokens (keep long & private in real apps)
jwt.secret=adajkwdiAHDJAKDNAKLDJoAJIODWAJKBdjkABNDJKANklwdjiosjfijsnfjknjkn677857jkhajkdijhdioa
